Bump virtualenv from 20.12.0 to 20.13.0 in /.github/workflows (#133)
Bumps [virtualenv](https://github.com/pypa/virtualenv) from 20.12.0 to 20.13.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/pypa/virtualenv/blob/main/docs/changelog.rst">virtualenv's changelog</a>.</em></p>
<blockquote>
<h2>v20.13.0 (2022-01-02)</h2>
<p>Features - 20.13.0</p>
<pre><code>- Add downloaded wheel information in the relevant JSON embed file to
  prevent additional downloads of the same wheel. - by :user:`mayeut`. (`[#2268](https://github.com/pypa/virtualenv/issues/2268) &lt;https://github.com/pypa/virtualenv/issues/2268&gt;`_)
<p>Bugfixes - 20.13.0
</code></pre></p>
<ul>
<li>Fix <code>AttributeError: 'bool' object has no attribute 'error'</code> when creating a
Python 2.x virtualenv on macOS - by <code>moreati</code>. (<code>[#2269](https://github.com/pypa/virtualenv/issues/2269) &lt;https://github.com/pypa/virtualenv/issues/2269&gt;</code>_)</li>
<li>Fix <code>PermissionError: [Errno 1] Operation not permitted</code> when creating a
Python 2.x virtualenv on macOS/arm64 - by <code>moreati</code>. (<code>[#2271](https://github.com/pypa/virtualenv/issues/2271) &lt;https://github.com/pypa/virtualenv/issues/2271&gt;</code>_)</li>
</ul>
<h2>v20.12.1 (2022-01-01)</h2>
<p>Bugfixes - 20.12.1</p>
<pre><code>- Try using previous updates of ``pip``, ``setuptools`` &amp; ``wheel``
  when inside an update grace period rather than always falling back
  to embedded wheels - by :user:`mayeut`. (`[#2265](https://github.com/pypa/virtualenv/issues/2265) &lt;https://github.com/pypa/virtualenv/issues/2265&gt;`_)
- New patch versions of ``pip``, ``setuptools`` &amp; ``wheel`` are now
  returned in the expected timeframe. - by :user:`mayeut`. (`[#2266](https://github.com/pypa/virtualenv/issues/2266) &lt;https://github.com/pypa/virtualenv/issues/2266&gt;`_)
- Manual upgrades of ``pip``, ``setuptools`` &amp; ``wheel`` are
  not discarded by a periodic update - by :user:`mayeut`. (`[#2267](https://github.com/pypa/virtualenv/issues/2267) &lt;https://github.com/pypa/virtualenv/issues/2267&gt;`_)
</code></pre>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/pypa/virtualenv/commit/568136cd8872e78a266411ca83b0cfc190acc090"><code>568136c</code></a> release 20.13.0</li>
<li><a href="https://github.com/pypa/virtualenv/commit/e813ac1fd3c0a21a7c2a2448650bbe6ac53b8753"><code>e813ac1</code></a> PyPy: glob for required dlls, check they exist (<a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2274">#2274</a>)</li>
<li><a href="https://github.com/pypa/virtualenv/commit/856933e30fb573f966150d6e2d568a81761b165b"><code>856933e</code></a> fix: Correctly remove bk dir when re-signing macOS Python 2.x executable (<a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2272">#2272</a>)</li>
<li><a href="https://github.com/pypa/virtualenv/commit/50c5591fe9f01dfbc46ceb5638a10b837514410c"><code>50c5591</code></a> fix: AttributeError on macOS creating a Python 2.x virtualenv (<a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2270">#2270</a>)</li>
<li><a href="https://github.com/pypa/virtualenv/commit/319a540001f68b60fd7367e31d5d7398dbd3a1ef"><code>319a540</code></a> feature: cache downloaded wheel information (<a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2276">#2276</a>)</li>
<li><a href="https://github.com/pypa/virtualenv/commit/5f65057501e9e6b86e02fe7d9a26649f65ce9254"><code>5f65057</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2275">#2275</a> from pypa/release-20.12.1</li>
<li><a href="https://github.com/pypa/virtualenv/commit/879926629d8c26856e225ee65b02fc75a72aa186"><code>8799266</code></a> release 20.12.1</li>
<li><a href="https://github.com/pypa/virtualenv/commit/4308ddb276962c6ffdf0285c809a81f6bef8dbb0"><code>4308ddb</code></a> feature: store version update source in embed JSON file (<a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2273">#2273</a>)</li>
<li><a href="https://github.com/pypa/virtualenv/commit/51408e689b3eb28d87cb4d9638b09e6e4d81f618"><code>51408e6</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/pypa/virtualenv/issues/2264">#2264</a> from pypa/release-20.12.0</li>
<li>See full diff in <a href="https://github.com/pypa/virtualenv/compare/20.12.0...20.13.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=virtualenv&package-manager=pip&previous-version=20.12.0&new-version=20.13.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>